### PR TITLE
Update yaml-language-server

### PR DESCRIPTION
**Pull request by AndreasMadsen**
The new yaml-language-server contains modern JavaScript that the umd-compat-loader does not understand.

Instead, load the yaml-language-server types directly from the source and set all it's dependencies as noParse.

---

Note, while the build runs and the tests passes. I'm not sure if the tests use the build or the source.

### CODE REVIEW

**Comment by InoUno** [comment]
Looks like you'll need to update the pnpm lockfile as well, since some packages in package.json have changed.

**Comment by AndreasMadsen** [comment]
Hi @InoUno, I tried to update with `pnpm install --no-frozen-lockfile` as instructed. However, the CI still complains. I don't understand what the issue is.

**Comment by AndreasMadsen** [comment]
Sorry @InoUno. The pnpm version I was using was too new. I managed to find the right version. The CI is happy now.

**Comment by AndreasMadsen** [comment]
Hi, @InoUno take your time. I just want to make sure this is not forgotten.

**Comment by AndreasMadsen** [comment]
The initial fix, build and completed all tests. However, I discovered that the tests don't run the GitHub build file. When running the build file from a test repo, there were import errors due to UMD files being loaded.

I have now fixed the UMD issues using a filepath transformer and my test repo works. I tried to create a test for the GitHub build file, but couldn't figure out how to pass the expected arguments.

**Comment by InoUno** [comment]
Thanks for being thorough!

It looks okay to me, so let's try it out

**Review by InoUno — APPROVED** [review]

**Pull request merged**
